### ISSUE TITLE
Compiler

### ISSUE THREAD

**Issue by Devil666face** [m4ul3r/writing_nimless#2]
What compiler you use for build 0x12 main_dll.bat
gcc(mingw)
or vcc(msvc)?

I have this error when build via gcc
```
 @minstance.nim.c.o:@minstance.nim:(.text$getProcAddressHash__utilsZgpa_u18+0x119): undefined reference to `strlen'
collect2.exe: error: ld returned 1 exit status
```

**Comment by m4ul3r** [comment]
It should use mingw by default and it looks like it is compiling with that from your error since `ld` is being used. 

Check a few things for `0x12`.

1. Make sure that you use the `dll_main.cfg`. This can be done by specifying it or copying and renaming it to `nim.cfg`

2. The main error is `strlen` is an undefined reference. At some step in the compilation that is being used, since it's a utility in the CRT we have to define it ourselves.
You can change the function declaration [in gpa.nim](https://github.com/m4ul3r/writing_nimless/blob/main/src/0x12%20-%20nimless_DLL/utils/gpa.nim#L5) that is defining our custom `strlenA` and add to the pragma to be: `{.inline, exportc: "strlen".}` to tell the compiler that this is strlen.

3. Change optimization levels from `-Os` to `-O2`, `-O1`, or `-O0`. They have different effects on what the compiler wants to include to optimize.

**Comment by Devil666face** [comment]
> По умолчанию он должен использовать mingw, и похоже, что он компилируется с учетом вашей ошибки, поскольку `ld` используется.
> 
> Проверьте несколько вещей, чтобы `0x12`.
> 
>     1. Убедитесь, что вы используете `dll_main.cfg`.  Это можно сделать, указав его или скопировав и переименовав в `nim.cfg`
> 
>     2. Основная ошибка заключается в `strlen`это неопределенная ссылка.  На каком-то этапе используемой компиляции, поскольку это утилита в CRT, мы должны определить ее самостоятельно. 
>        Вы можете изменить объявление функции [ в gpa.nim ](https://github.com/m4ul3r/writing_nimless/blob/main/src/0x12%20-%20nimless_DLL/utils/gpa.nim#L5) , которое определяет нашу пользовательскую функцию. `strlenA` и добавьте в прагму следующее: `{.inline, exportc: "strlen".}` чтобы сообщить компилятору, что это strlen.
> 
>     3. Изменить уровни оптимизации с `-Os` к `-O2`,  `-O1`, или `-O0`.  Они по-разному влияют на то, что компилятор хочет включить для оптимизации.

`-O2`, `-O1`, `-O0` fix it
But i have detect on WinDef ))))))))
